version: 1.2
workflows:
  - name: GATKSVPipelineBatch
    subclass: WDL
    primaryDescriptorPath: /wdl/GATKSVPipelineBatch.wdl
  - name: GATKSVPipelineSingleSample
    subclass: WDL
    primaryDescriptorPath: /wdl/GATKSVPipelineSingleSample.wdl
